name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *' # Automatsko osvežavanje svaka 2 sata
  workflow_dispatch:      # Omogućava ti da ručno klikneš "Run workflow" u GitHub-u

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'aihubnews' # OBAVEZNO: Ovde upiši tačno ime tvog projekta sa Cloudflare-a
          directory: './dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
